//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('CartSystem')
export class CartSystemEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  userID: number;

  @Column('integer', { nullable: true })
  itemIDs: number;

  @Column('integer', { nullable: true })
  quantities: number;

  @Column('text', { nullable: true })
  checkoutStatus: string;
}
