//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Items')
export class ItemsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  itemName: string;

  @Column('text', { nullable: true })
  category: string;

  @Column('integer', { nullable: true })
  quantity: number;
}
