//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const CartSystemTitle = () => {
  const record = useRecordContext();
  return <span>CartSystem {record ? `"${record.userID}"` : ''}</span>;
};

export const CartSystemList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <ReferenceField source="userID" reference="Users" />
      <ReferenceField source="itemIDs" reference="Items" />
      <NumberField source="quantities" />
      <TextField source="checkoutStatus" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const CartSystemEdit = () => (
  <Edit title={<CartSystemTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="userID" reference="Users" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="itemIDs" reference="Items" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="quantities" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="checkoutStatus" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const CartSystemCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="userID" reference="Users" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="itemIDs" reference="Items" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="quantities" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="checkoutStatus" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  <ReferenceInput source="userID" label="userID" reference="Users" alwaysOn />,
  <ReferenceInput
    source="itemIDs"
    label="itemIDs"
    reference="Items"
    alwaysOn
  />,
  ,
  ,
];
