//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Users: {
      name: 'Users',
      fields: { name: 'Name', address: 'Address', email: 'Email', id: 'id' },
    },
    CharitiesInstitutes: {
      name: 'Charities/institutes',
      fields: {
        address: 'Address',
        organisationName: 'Organisation Name',
        description: 'Description',
        locations: 'Locations',
        id: 'id',
      },
    },
    Admins: {
      name: 'Admins',
      fields: { name: 'Name', email: 'Email', roles: 'Roles', id: 'id' },
    },
    Donations: {
      name: 'Donations',
      fields: {
        userID: 'User Id',
        charityInstituteID: 'Charity Institute Id',
        donationType: 'Donation Type',
        amount: 'Amount',
        itemsList: 'Items List',
        status: 'Status',
        id: 'id',
      },
    },
    Items: {
      name: 'Items',
      fields: {
        itemName: 'Item Name',
        category: 'Category',
        quantity: 'Quantity',
        id: 'id',
      },
    },
    CartSystem: {
      name: 'Cart System',
      fields: {
        userID: 'User Id',
        itemIDs: 'Item Ids',
        quantities: 'Quantities',
        checkoutStatus: 'Checkout Status',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Users: {
      name: 'Users (fr)',
      fields: {
        name: 'Name (fr)',
        address: 'Address (fr)',
        email: 'Email (fr)',
        id: 'id',
      },
    },
    CharitiesInstitutes: {
      name: 'Charities/institutes (fr)',
      fields: {
        address: 'Address (fr)',
        organisationName: 'Organisation Name (fr)',
        description: 'Description (fr)',
        locations: 'Locations (fr)',
        id: 'id',
      },
    },
    Admins: {
      name: 'Admins (fr)',
      fields: {
        name: 'Name (fr)',
        email: 'Email (fr)',
        roles: 'Roles (fr)',
        id: 'id',
      },
    },
    Donations: {
      name: 'Donations (fr)',
      fields: {
        userID: 'User Id (fr)',
        charityInstituteID: 'Charity Institute Id (fr)',
        donationType: 'Donation Type (fr)',
        amount: 'Amount (fr)',
        itemsList: 'Items List (fr)',
        status: 'Status (fr)',
        id: 'id',
      },
    },
    Items: {
      name: 'Items (fr)',
      fields: {
        itemName: 'Item Name (fr)',
        category: 'Category (fr)',
        quantity: 'Quantity (fr)',
        id: 'id',
      },
    },
    CartSystem: {
      name: 'Cart System (fr)',
      fields: {
        userID: 'User Id (fr)',
        itemIDs: 'Item Ids (fr)',
        quantities: 'Quantities (fr)',
        checkoutStatus: 'Checkout Status (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
